"""Phase 11 Final End-to-End Export & Provenance Validation Suite.

Executes standalone Python verification of exported ZIP archives generated by
the real Next.js /api/export endpoint:
1. ZIP integrity (opens, central directory, no duplicates)
2. Artifacts inspection (manifest, analysis, provenance, geojson, readme, metadata, rasters)
3. Real Sentinel-2 Bhadla metadata consistency
4. Cluster area configuration check (authoritative 900 m2 / 9 px)
5. Independent GeoJSON RFC 7946 validation
6. Security and secret exclusion check
7. Standalone bundle portability extraction
"""

import json
import os
import shutil
import subprocess
import sys
import tempfile
import zipfile
import pytest

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "..", "web", "tests", "output")
BHADLA_ZIP = os.path.join(OUTPUT_DIR, "bhadla_real_export.zip")
BENCHMARK_ZIP = os.path.join(OUTPUT_DIR, "benchmark_export.zip")


@pytest.fixture(scope="session", autouse=True)
def ensure_test_zips_exist():
    """Ensure Next.js E2E test has generated the test ZIP bundles if not already on disk."""
    if not os.path.exists(BHADLA_ZIP) or not os.path.exists(BENCHMARK_ZIP):
        web_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "web"))
        cmd = ["npx.cmd" if sys.platform == "win32" else "npx", "tsx", "scripts/test_export_route_e2e.ts"]
        subprocess.run(cmd, cwd=web_dir, check=True)



def test_zip_integrity_and_artifacts():
    """Verify ZIP opens, central directory is valid, no duplicates, all required artifacts present."""
    assert os.path.exists(BHADLA_ZIP), f"Missing {BHADLA_ZIP}"
    assert os.path.exists(BENCHMARK_ZIP), f"Missing {BENCHMARK_ZIP}"

    for zip_path in [BHADLA_ZIP, BENCHMARK_ZIP]:
        with zipfile.ZipFile(zip_path, "r") as zf:
            # Test central directory / corruption
            corrupt = zf.testzip()
            assert corrupt is None, f"Corrupted file found in {zip_path}: {corrupt}"

            namelist = zf.namelist()
            # No duplicate filenames
            assert len(namelist) == len(set(namelist)), f"Duplicate entries in {zip_path}: {namelist}"

            # Required artifacts
            required = [
                "manifest.json",
                "analysis.json",
                "provenance.json",
                "change_clusters.geojson",
                "README.md",
                "before/scene_metadata.json",
                "after/scene_metadata.json",
                "rasters/raster_info.txt",
            ]
            for req in required:
                assert req in namelist, f"Missing {req} in {zip_path}"


def test_benchmark_visual_artifacts():
    """Verify benchmark ZIP contains visual change mask PNG if available."""
    with zipfile.ZipFile(BENCHMARK_ZIP, "r") as zf:
        namelist = zf.namelist()
        if "rasters/change_mask.png" in namelist:
            data = zf.read("rasters/change_mask.png")
            # Verify PNG signature \x89PNG\r\n\x1a\n
            assert data.startswith(b"\x89PNG\r\n\x1a\n"), "change_mask.png must be valid PNG"


def test_real_sentinel2_metadata_consistency():
    """Verify that exported Real Sentinel-2 Bhadla values match the actual analysis result."""
    with zipfile.ZipFile(BHADLA_ZIP, "r") as zf:
        manifest = json.loads(zf.read("manifest.json").decode("utf-8"))
        analysis = json.loads(zf.read("analysis.json").decode("utf-8"))
        prov = json.loads(zf.read("provenance.json").decode("utf-8"))
        geojson = json.loads(zf.read("change_clusters.geojson").decode("utf-8"))

        # Location & AOI
        assert manifest["location_id"] == "LOC_EO_01_BHADLA_SOLAR"
        assert "Bhadla Solar Park" in manifest["location_name"]
        assert manifest["aoi"]["min_lat"] == 27.48
        assert manifest["aoi"]["min_lon"] == 71.85
        assert manifest["aoi"]["max_lat"] == 27.60
        assert manifest["aoi"]["max_lon"] == 72.05

        # T1 / T2 Real Sentinel-2 scene IDs and dates
        assert manifest["t1_scene_id"] == "S2C_MSIL2A_20260926T054641_R048_T43RBL_20260926T085113"
        assert manifest["t2_scene_id"] == "S2B_MSIL2A_20261001T054639_R048_T42RYR_20261001T075536"
        assert "2026-09-26" in manifest["t1_acquisition_timestamp"]
        assert "2026-10-01" in manifest["t2_acquisition_timestamp"]
        assert manifest["t1_cloud_percentage"] == 0.0
        assert manifest["t2_cloud_percentage"] == 0.0

        # Quantitative Change Metrics
        assert manifest["changed_pixel_count"] == 5120
        assert manifest["change_area"]["ha"] == 51.2
        assert manifest["change_area"]["m2"] == 512000
        assert manifest["number_of_detected_clusters"] == 2
        assert manifest["threshold"]["value"] == 0.285

        # Clusters
        assert len(geojson["features"]) == 2
        f0 = geojson["features"][0]
        assert f0["properties"]["cluster_id"] == "CLUST_001"
        assert f0["properties"]["classification"] == "BUILT_UP_CONSTRUCTION"
        assert f0["properties"]["confidence"] == 0.88
        assert f0["properties"]["area_ha"] == 32.0
        assert f0["properties"]["analyst_decision"] == "CONFIRMED"

        f1 = geojson["features"][1]
        assert f1["properties"]["cluster_id"] == "CLUST_002"
        assert f1["properties"]["classification"] == "BUILT_UP_CONSTRUCTION"
        assert f1["properties"]["confidence"] == 0.82
        assert f1["properties"]["area_ha"] == 19.2
        assert f1["properties"]["analyst_decision"] == "CONFIRMED"

        # Analyst status
        assert manifest["analyst_status"] == "CONFIRMED"
        assert prov["analyst_actions"]["overall_status"] == "CONFIRMED"


def test_cluster_area_configuration_consistency():
    """Verify provenance reports the authoritative configured minimum cluster area (900 m2 / 9 px)."""
    with zipfile.ZipFile(BHADLA_ZIP, "r") as zf:
        prov = json.loads(zf.read("provenance.json").decode("utf-8"))
        min_area_reported = prov["processing"]["minimum_cluster_area"]
        assert "900 m²" in min_area_reported or "9 contiguous pixels" in min_area_reported, (
            f"Provenance reported '{min_area_reported}' but authoritative configuration is 900 m² / 9 px."
        )


def test_independent_geojson_validation():
    """Validates GeoJSON FeatureCollection independently according to RFC 7946."""
    for zip_path in [BHADLA_ZIP, BENCHMARK_ZIP]:
        with zipfile.ZipFile(zip_path, "r") as zf:
            geojson = json.loads(zf.read("change_clusters.geojson").decode("utf-8"))

            assert geojson["type"] == "FeatureCollection"
            assert "features" in geojson
            assert len(geojson["features"]) > 0

            for idx, feature in enumerate(geojson["features"]):
                assert feature["type"] == "Feature", f"Feature[{idx}] not Feature"
                assert "geometry" in feature
                geom = feature["geometry"]
                assert geom["type"] == "Polygon"

                coords = geom["coordinates"]
                assert isinstance(coords, list) and len(coords) >= 1
                ring = coords[0]
                assert len(ring) >= 4, f"Feature[{idx}] ring too small: {len(ring)}"

                # Closed ring check
                assert ring[0] == ring[-1], f"Feature[{idx}] ring not closed: {ring[0]} != {ring[-1]}"

                # WGS84 range check [lon, lat]
                for pt in ring:
                    lon, lat = pt[0], pt[1]
                    assert -180.0 <= lon <= 180.0, f"Lon {lon} outside [-180, 180]"
                    assert -90.0 <= lat <= 90.0, f"Lat {lat} outside [-90, 90]"

                # Properties check
                props = feature["properties"]
                assert "cluster_id" in props
                assert "classification" in props
                assert "confidence" in props
                assert "area_m2" in props
                assert "area_ha" in props
                assert "centroid" in props
                assert "source_scene_ids" in props
                assert "acquisition_dates" in props


def test_provenance_security_and_token_sanitization():
    """Inspects every exported artifact to guarantee zero leaked secrets or tokens."""
    forbidden_tokens = ["TEMP_SECRET_KEY", "TEMP_SIGNATURE_HASH", "token=", "sig=", "bearer", "process.env"]

    for zip_path in [BHADLA_ZIP, BENCHMARK_ZIP]:
        with zipfile.ZipFile(zip_path, "r") as zf:
            for name in zf.namelist():
                content = zf.read(name)
                # Check text files
                if name.endswith((".json", ".geojson", ".md", ".txt")):
                    text = content.decode("utf-8")
                    for token in forbidden_tokens:
                        assert token not in text, f"Found forbidden secret '{token}' in {name} of {zip_path}"

            # Verify public URLs retain useful scene identifiers while stripping tokens
            before_meta = json.loads(zf.read("before/scene_metadata.json").decode("utf-8"))
            preview_url = before_meta.get("preview_url", "")
            if preview_url:
                assert "item=" in preview_url, "preview_url must retain public item ID"
                assert "token=" not in preview_url, "preview_url must strip security token"


def test_bundle_portability():
    """Extracts bundle to clean directory and verifies standalone readability without TerraLens."""
    with tempfile.TemporaryDirectory() as tmpdir:
        with zipfile.ZipFile(BHADLA_ZIP, "r") as zf:
            zf.extractall(tmpdir)

        # 1. manifest.json standalone parse
        with open(os.path.join(tmpdir, "manifest.json"), "r", encoding="utf-8") as f:
            manifest = json.load(f)
            assert manifest["project_name"] == "TerraLens AI"
            assert manifest["problem_statement_id"] == "SIH26227"

        # 2. change_clusters.geojson standalone parse
        with open(os.path.join(tmpdir, "change_clusters.geojson"), "r", encoding="utf-8") as f:
            geojson = json.load(f)
            assert geojson["type"] == "FeatureCollection"

        # 3. README.md readability
        with open(os.path.join(tmpdir, "README.md"), "r", encoding="utf-8") as f:
            readme = f.read()
            assert "# TerraLens AI Analysis Report" in readme
            assert "## Quality & False-Alarm Controls" in readme
            assert "NOT calibrated probabilities" in readme

        # 4. provenance.json lineage readability
        with open(os.path.join(tmpdir, "provenance.json"), "r", encoding="utf-8") as f:
            prov = json.load(f)
            assert prov["lineage_standard"] == "TerraLens Structured Auditable Lineage"
            assert "blockchain" not in json.dumps(prov).lower()
