import { NextRequest, NextResponse } from "next/server";
import { getLocationById, getChangeAnalysis } from "@/lib/data";

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const locationId = body.location_id;
    const format = body.format || "markdown";
    const analystDecision = body.analyst_decision || body.verdict || "VERIFIED_TRUE_CHANGE";
    const analystNotes = body.analyst_notes || "";

    if (!locationId) {
      return NextResponse.json({ error: "Field 'location_id' is required" }, { status: 400 });
    }

    const location = getLocationById(locationId);
    const analysis = getChangeAnalysis(locationId);

    if (!location || !analysis) {
      return NextResponse.json({ error: `Location or analysis not found for: ${locationId}` }, { status: 404 });
    }

    const timestamp = new Date().toISOString();

    if (format === "markdown") {
      const mdContent = `# TERRALENS AI — ANALYTICAL EVIDENCE DOSSIER
**Problem Statement:** SIH26227 (Smart India Hackathon 2026)  
**Export Date:** ${timestamp}  
**Analyst Verdict:** ${analystDecision}  

---

## 1. TARGET INFORMATION
- **Location ID:** \`${location.location_id}\`
- **Location Name:** ${location.name}
- **Description:** ${location.description}
- **Coordinates:** ${location.latitude.toFixed(4)}°N, ${location.longitude.toFixed(4)}°E
- **Sensor:** ${location.primary_sensor}

## 2. CHANGE DETECTION METRICS
- **Detection Status:** ${analysis.status}
- **Classification:** ${analysis.change_type}
- **Algorithm:** ${analysis.detector_label} (\`${analysis.detector_name}\`)
- **Changed Pixels:** ${analysis.changed_pixels.toLocaleString()} / ${analysis.total_pixels.toLocaleString()}
- **Change Ratio:** ${(analysis.change_ratio * 100).toFixed(2)}%
- **Analytical Confidence Score:** ${((analysis.confidence_score ?? 0) * 100).toFixed(1)}%
- **Extracted Change Regions:** ${analysis.change_regions?.length || 0} clusters

## 3. CONFIDENCE BREAKDOWN
- **Signal Contrast:** ${analysis.confidence_breakdown?.signal_contrast?.toFixed(3) ?? "N/A"}
- **Spatial Coherence:** ${analysis.confidence_breakdown?.spatial_coherence?.toFixed(3) ?? "N/A"}
- **Alignment Penalty:** ${analysis.confidence_breakdown?.alignment_penalty?.toFixed(3) ?? "0.000"}
- **Quality Penalty:** ${analysis.confidence_breakdown?.quality_penalty?.toFixed(3) ?? "0.000"}

## 4. AUDIT & PROVENANCE CHAIN
1. **Semantic Discovery:** CLIP ViT-B/32 query projection -> FAISS L2 Normalized Cosine Search.
2. **Temporal Alignment:** Sub-pixel affine verification -> Resolution standardization.
3. **Radiometric Correction:** Global histogram contrast & illumination normalization.
4. **Differentiation:** Absolute luminance subtraction ($|T_2 - T_1|$).
5. **False-Alarm Suppression:** Morphological opening + Minimum region thresholding (20 px).
6. **Region Extraction:** 8-way connected components labeling with centroid computation.

## 5. ANALYST REVIEW
- **Verdict:** ${analystDecision}
- **Review Notes:** ${analystNotes || "Confirmed multi-temporal change signature consistent with satellite observation."}

---
*Generated by TerraLens AI Intelligence Engine — Smart India Hackathon 2026*
`;

      return NextResponse.json({
        filename: `terralens_dossier_${location.location_id}.md`,
        format: "markdown",
        content: mdContent,
      });
    }

    // Default JSON structure
    const jsonDossier = {
      project: "TerraLens AI",
      sih_problem: "SIH26227",
      export_timestamp: timestamp,
      adjudication: {
        verdict: analystDecision,
        notes: analystNotes,
      },
      target: {
        location_id: location.location_id,
        name: location.name,
        description: location.description,
        coordinates: {
          latitude: location.latitude,
          longitude: location.longitude,
        },
        bounding_box: location.bounding_box,
        sensor: location.primary_sensor,
      },
      detection_results: analysis,
      provenance: [
        { stage: "vector_retrieval", engine: "CLIP ViT-B/32 + Normalized Cosine Search" },
        { stage: "alignment", method: "Spatial Homography & Scale Check" },
        { stage: "radiometric_normalization", method: "Mean & Variance Contrast Equalization" },
        { stage: "difference_operator", method: "Absolute Luminance Subtraction" },
        { stage: "false_alarm_reduction", method: "Morphological Open + Min Component Filter (20px)" },
        { stage: "region_clustering", method: "8-connectivity Connected Component Labeling" },
      ],
    };

    return NextResponse.json({
      filename: `terralens_dossier_${location.location_id}.json`,
      format: "json",
      content: jsonDossier,
    });
  } catch (err: any) {
    return NextResponse.json({ error: "Export failed", details: String(err) }, { status: 500 });
  }
}
